name: ambari-tester
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: zrain/ambari-tester:0.0.1
    steps:        
      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Dbugger
        shell: bash -e -o pipefail {0}
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          whoami
          pwd
          echo $SHELL
          java -version
          mvn -version
          mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout

      - name: Check ambari-metrics
        id: check_ambari_metrics
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: 'ambari-metrics'


