name: ambari-tester
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: Setup python3.9
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.9'
          
      - name: Setup java & maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Install chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup required dyn env
        run: |
          pip install distro
          export CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Check ambari-metrics
        id: check_ambari_metrics
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: 'ambari-metrics'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Ambari Metrics Build (deps)
        if: steps.check_ambari_metrics.outputs.files_exists == 'true'
        working-directory: ambari-metrics
        run: mvn -T 3C install -DskipSurefireTests -DskipPythonTests -Dmaven.test.failure.ignore -DskipTests -Dfindbugs.skip -Drat.skip -Dmaven.artifact.threads=10 -X
      
      - name: Ambari Service Advisor
        run: mvn -T 3C -am install -pl ambari-serviceadvisor -DskipSurefireTests -DskipPythonTests -Dmaven.test.failure.ignore -DskipTests -Dfindbugs.skip -Drat.skip -Dmaven.artifact.threads=10

      - name: RAT
        run: mvn org.apache.rat:apache-rat-plugin:check -Dmaven.artifact.threads=10

      - name: Ambari WebUI Tests
        run: mvn -X -T 2C -am test -pl ambari-web,ambari-admin -Dmaven.artifact.threads=10 -Drat.skip
        
      - name: Ambari Agent Tests
        run: mvn -X -Dmaven.test.failure.ignore=true -am test -pl ambari-agent -Dmaven.artifact.threads=10 -Drat.skip

      - name: Ambari Server PyTests
        run: mvn -X -am test -pl ambari-server -DskipSurefireTests -Dmaven.test.failure.ignore -Dmaven.artifact.threads=10 -Drat.skip -Dcheckstyle.skip
