name: ambari-tester
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: zrain/ambari-tester:0.0.1
    steps:        
      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Debugger
        shell: bash -e -o pipefail {0}
        run: |
          export CHROME_BIN=/usr/local/chrome-linux/chrome
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=/usr/local/chrome-linux:$CHROME_BIN:$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          whoami
          pwd
          echo $SHELL
          java -version
          mvn -version
          chrome --version

      - name: Check ambari-metrics
        id: check_ambari_metrics
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: 'ambari-metrics'

      - name: Ambari Metrics Build (deps)
        if: steps.check_ambari_metrics.outputs.files_exists == 'true'
        working-directory: ambari-metrics
        shell: bash -e -o pipefail {0}
        run: |
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          mvn -T 3C install -DskipSurefireTests -DskipPythonTests -Dmaven.test.failure.ignore -DskipTests -Dfindbugs.skip -Drat.skip -Dmaven.artifact.threads=10 -X
      
      - name: Ambari Service Advisor
        shell: bash -e -o pipefail {0}
        run: |
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          mvn -T 3C -am install -pl ambari-serviceadvisor -DskipSurefireTests -DskipPythonTests -Dmaven.test.failure.ignore -DskipTests -Dfindbugs.skip -Drat.skip -Dmaven.artifact.threads=10

      - name: RAT
        shell: bash -e -o pipefail {0}
        run: |
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          mvn org.apache.rat:apache-rat-plugin:check -Dmaven.artifact.threads=10

      - name: Ambari-web Tests
        shell: bash -e -o pipefail {0}
        run: |
          export CHROME_BIN=/usr/local/chrome-linux/chrome
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          mvn -X -T 2C -am test -pl ambari-web -Dmaven.artifact.threads=10 -Drat.skip

      - name: Ambari-admin Tests
        shell: bash -e -o pipefail {0}
        run: |
          export CHROME_BIN=/usr/local/chrome-linux/chrome
          export JAVA_HOME=/usr/local/jdk8
          export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
          export MAVEN_HOME=/usr/local/maven
          export NODE_HOME=/usr/local/node
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$NODE_HOME/bin:$PATH
          apt-get install -y git
          mvn -X -T 2C -am test -pl ambari-admin -Dmaven.artifact.threads=10 -Drat.skip
          
